module.exports = {
  async up(queryInterface, Sequelize) {
    const apartArr = [
      {
        ownerId: 1,
        cathegoryId: 1,
        price: 40000,
        countOfRooms: 1,
        address: 'Москва, ул. Цимлянская, д. 5',
        description: 'Сдается просторная, светлая, уютная квартира по привлекательной цене рядом с метро! Есть все необходимое для комфортного проживания: шкафы, кровати, кухонная мебель, холодильник, стиральная машина. Окна выходят в тихий, зелёный двор. Интеллигентные, дружные соседи. Развитая инфраструктура, рядом магазины, школа, колледж, больница, парковка, торговые центры',
        image: 'https://bouw.ru/wp-content/uploads/2021/10/36-1.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ownerId: 2,
        cathegoryId: 3,
        price: 12000,
        countOfRooms: 1,
        address: 'Москва, ул. Яблочная, д. 35',
        description: 'Сдам комнату в 1 минуте от метро Менделеевская, в очень хорошем состоянии в малонаселенной квартире в соседних комнатах проживает один молодой мужчина и пожилая женщина. Для одного человека. В услугах риелтора не нуждаюсь. Просьба звонить с 10.00 до 22.00.',
        image: 'https://arhitektfoto.ru/wp-content/uploads/spalnya-v-apartementah-oko-02.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ownerId: 3,
        cathegoryId: 2,
        price: 120000,
        countOfRooms: 5,
        address: 'Москва, ул. Строителей, д. 2',
        description: 'Предлагается в аренду двух этажный дом в уникальном месте, рядом с метро.  После косметического ремонта. На первом этаже расположились две просторные комнаты, санузел, кухня. На втором этаже три комнаты с большими окнами. На чердаке можно организовать дополнительное жилое пространство. Дом расположен на участке 10 соток. Огороженная территория. Развитая инфраструктура.',
        image: 'https://i.pinimg.com/originals/50/a9/8f/50a98f3608b6f992f6b68154c743f423.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ownerId: 4,
        cathegoryId: 1,
        price: 110000,
        countOfRooms: 2,
        address: 'Москва, ул. Краснопресненская наб., 2/1',
        description: 'Великолепная 2-комнатная квартира в сталинском доме, расположенная на 8 этаже 11 этажного здания. Потолки 3 м. Спален: 1, санузлов: 1. Общая площадь: 68 кв.м. Ремонт в уникальном авторском стиле. Квартира полностью с мебелью, вывоз обсуждается. Посудомоечная машина, холодильник, приточно-вытяжная система вентиляции в спальной комнате, ванна, стиральная машина, телевизор, высокоскоростной интернет. Консьерж',
        image: 'https://dizainexpert.ru/wp-content/uploads/2019/09/kvartira-v-svetlyx-tonax-i-sovremennom-stile-varianty.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ownerId: 1,
        cathegoryId: 1,
        price: 70000,
        countOfRooms: 2,
        address: 'Москва, ул. Трехгорный Вал, 5',
        description: 'Чистая, уютная, светлая квартира, очень тихое и живописное место, парковая зона, рядом Москва Сити. Вся необходимая современная мебель и бытовая техника для проживания имеется. Видеонаблюдение в подъезде (оплата электроэнергии и водоотведения по счетчикам). Красивый вид из окон, вся необходимая инфраструктура в шаговой доступности, рядом сад, школа, сетевые магазины. ',
        image: 'https://studio-ta.ru/wp-content/uploads/2020/05/Loft77-apartment-12.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ownerId: 2,
        cathegoryId: 3,
        price: 25000,
        countOfRooms: 1,
        address: 'Москва, Малый Левшинский пер., 14/9С1',
        description: 'Центр! Самый элитный  район Москвы) Современная, красивая квартира. Очень просторная и красивая комната. Вместе с кроватью и диваном !) Огромный шкаф купе. Есть все необходимое для комфортного проживания в квартире. ',
        image: 'https://mykaleidoscope.ru/uploads/posts/2021-04/1617233607_28-p-kvartira-v-stile-modern-28.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ownerId: 4,
        cathegoryId: 3,
        price: 40000,
        countOfRooms: 3,
        address: 'Москва, Оружейный пер., 25С1а',
        description: 'Сдам комнату в трёхкомнатной квартире с балконом на Чистые Пруды и театр современник! Новый евроремонт , огромная высокая кровать кинг сайз с ортопедическим матрасом , вся необходимая мебель и техника , джакузи, посудомоечная машина , полы с подогревом , телевизор со smart tv и т.д.',
        image: 'https://dizainexpert.ru/wp-content/uploads/2020/07/studiya-25-kvadratov-foto_23.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ownerId: 3,
        cathegoryId: 2,
        price: 250000,
        countOfRooms: 1,
        address: ' Речник поселок, ул. Верхняя',
        description: 'Сдаётся удобный дом для большой семьи в Москве в Крылатском, посёлке Речник. Жилая площадь дома 300 кв. метров. Расположен в экологически чистом районе,  в парке Москворецкий, в простой доступности от  Новорижского шоссе, проспекта маршала Жукова, Рублевского шоссе.',
        image: 'https://m-strana.ru/upload/iblock/ec1/ec16e2e4e05d6ad1b1dcdd323d12d35f.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ownerId: 3,
        cathegoryId: 2,
        price: 180000,
        countOfRooms: 1,
        address: 'Рублево поселок, Рублевское шоссе, 2-й км',
        description: 'В окружении соснового леса, идеальное место для здорового образа жизни, сочетание хвойного целебного воздуха с комфортом Московской квартиры. В пешей доступности Москва-река с пляжем и рыбалкой, культурным центром Рублево, храмом, спортивной секцией',
        image: 'https://loftecomarket.ru/wp-content/uploads/0/d/5/0d5ba18b2d146d4c6ec80d8bf59d1a6b.jpeg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ];
    await queryInterface.bulkInsert('Appartments', apartArr, {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Appartments', null, {});
  },
};
